-- CreateTable
CREATE TABLE "clients" (
    "id" SERIAL NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "clientType" TEXT NOT NULL DEFAULT '',
    "registrationType" TEXT NOT NULL DEFAULT 'Regular',
    "email" TEXT NOT NULL DEFAULT '',
    "phone" TEXT NOT NULL DEFAULT '',
    "altPhone" TEXT NOT NULL DEFAULT '',
    "gstin" TEXT NOT NULL DEFAULT '',
    "pan" TEXT NOT NULL DEFAULT '',
    "clientSince" TIMESTAMP(3),
    "address" TEXT NOT NULL DEFAULT '',
    "regAddr1" TEXT NOT NULL DEFAULT '',
    "regAddr2" TEXT NOT NULL DEFAULT '',
    "regCity" TEXT NOT NULL DEFAULT '',
    "regState" TEXT NOT NULL DEFAULT '',
    "regPin" TEXT NOT NULL DEFAULT '',
    "regCountry" TEXT NOT NULL DEFAULT 'India',
    "shipSameAsRegistered" BOOLEAN NOT NULL DEFAULT true,
    "shipSameAsBilling" BOOLEAN NOT NULL DEFAULT false,
    "shipAddr1" TEXT NOT NULL DEFAULT '',
    "shipAddr2" TEXT NOT NULL DEFAULT '',
    "shipCity" TEXT NOT NULL DEFAULT '',
    "shipState" TEXT NOT NULL DEFAULT '',
    "shipPin" TEXT NOT NULL DEFAULT '',
    "shipCountry" TEXT NOT NULL DEFAULT 'India',
    "billingMode" TEXT NOT NULL DEFAULT 'shipping',
    "billAddr1" TEXT NOT NULL DEFAULT '',
    "billAddr2" TEXT NOT NULL DEFAULT '',
    "billCity" TEXT NOT NULL DEFAULT '',
    "billState" TEXT NOT NULL DEFAULT '',
    "billPin" TEXT NOT NULL DEFAULT '',
    "billCountry" TEXT NOT NULL DEFAULT 'India',
    "paymentTerms" TEXT NOT NULL DEFAULT '',
    "priceList" TEXT NOT NULL DEFAULT '',
    "openingBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "creditLimit" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "creditDays" INTEGER NOT NULL DEFAULT 0,
    "contactPerson" TEXT NOT NULL DEFAULT '',
    "contactDesignation" TEXT NOT NULL DEFAULT '',
    "contactPhone" TEXT NOT NULL DEFAULT '',
    "contactEmail" TEXT NOT NULL DEFAULT '',
    "modifiedBy" TEXT NOT NULL DEFAULT 'Admin',
    "modifiedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "clients_code_key" ON "clients"("code");
