// Seeds the `products` table with the same static product list that used to
// live hardcoded in the Flutter app (lib/app/modules/products/controllers/
// products_controller.dart, now commented out there). Looks up each
// product's category/sub-category by name so it links to the real rows
// already seeded by seed.js.
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const products = [
  {
    name: 'CF Blanket 1260°C (64 kg/m³)',
    sku: 'CFB-1260-64',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Blanket',
    unit: 'Roll',
    sellingPrice: 2800,
    costPrice: 1900,
    currentStock: 45,
    minimumStock: 10,
    brand: 'SIMWOOL',
    hsnCode: '68061000',
    description:
      'Standard grade ceramic fiber blanket for high temperature insulation up to 1260°C.',
    taxPercent: 18,
    densityVariants: ['64 kg/m³'],
    modifiedBy: 'Chinmay Modi',
    modifiedAt: new Date(2026, 6, 10, 14, 40),
  },
  {
    name: 'CF Blanket 1260°C (96 kg/m³)',
    sku: 'CFB-1260-96',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Blanket',
    unit: 'Roll',
    sellingPrice: 3500,
    costPrice: 2400,
    currentStock: 32,
    minimumStock: 10,
    brand: 'SIMWOOL',
    hsnCode: '68061000',
    taxPercent: 18,
    densityVariants: ['96 kg/m³'],
    modifiedBy: 'Riya Patel',
    modifiedAt: new Date(2026, 5, 30, 9, 2),
  },
  {
    name: 'CF Blanket 1260°C (128 kg/m³)',
    sku: 'CFB-1260-128',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Blanket',
    unit: 'Roll',
    sellingPrice: 4200,
    costPrice: 2900,
    currentStock: 8,
    minimumStock: 10,
    brand: 'SIMWOOL',
    hsnCode: '68061000',
    taxPercent: 18,
    densityVariants: ['128 kg/m³'],
  },
  {
    name: 'CF Blanket 1425°C (96 kg/m³)',
    sku: 'CFB-1425-96',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Blanket',
    unit: 'Roll',
    sellingPrice: 6500,
    costPrice: 4500,
    currentStock: 15,
    minimumStock: 5,
    brand: 'SIMWOOL',
    hsnCode: '68061000',
    taxPercent: 18,
    densityVariants: ['96 kg/m³'],
  },
  {
    name: 'CF Bulk (Standard 1260°C)',
    sku: 'CFB-SBF-001',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Bulk (Loose Fiber)',
    unit: 'Kilogram (kg)',
    sellingPrice: 350,
    costPrice: 250,
    currentStock: 120,
    minimumStock: 25,
    brand: 'SIMWOOL',
    hsnCode: '68061000',
    taxPercent: 18,
  },
  {
    name: 'CF Module (1260°C)',
    sku: 'CFM-1260-001',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Module',
    unit: 'Piece (pcs)',
    sellingPrice: 1200,
    costPrice: 850,
    currentStock: 28,
    minimumStock: 5,
    brand: 'SIMWOOL',
    hsnCode: '68061000',
    taxPercent: 18,
  },
  {
    name: 'CF Board Grade 1260',
    sku: 'CFBD-1260',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Board',
    unit: 'Piece (pcs)',
    sellingPrice: 850,
    costPrice: 600,
    currentStock: 40,
    minimumStock: 10,
    brand: 'SIMVAC',
    hsnCode: '68061000',
    taxPercent: 18,
    boardVariants: ['Normal Board'],
  },
  {
    name: 'CF Board Grade 1425 (Zirconia)',
    sku: 'CFBD-1425',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Board',
    unit: 'Piece (pcs)',
    sellingPrice: 1650,
    costPrice: 1100,
    currentStock: 0,
    minimumStock: 5,
    brand: 'SIMVAC',
    hsnCode: '68061000',
    taxPercent: 18,
    boardVariants: ['Vacuum Formed Board'],
  },
  {
    name: 'CF Paper (1260°C, 5mm)',
    sku: 'CFP-1260-5',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Ceramic Fiber Paper',
    unit: 'Roll',
    sellingPrice: 480,
    costPrice: 320,
    currentStock: 22,
    minimumStock: 5,
    brand: 'SIMWOOL',
    hsnCode: '68061000',
    taxPercent: 18,
    thicknessVariants: ['5 mm'],
  },
  {
    name: 'Heatshield Blanket',
    sku: 'HSB-001',
    categoryName: 'Ceramic Fiber Products',
    subCategoryName: 'Heatshield Blanket',
    unit: 'Piece (pcs)',
    sellingPrice: 3200,
    costPrice: 2200,
    currentStock: 12,
    minimumStock: 3,
    hsnCode: '68061000',
    taxPercent: 18,
  },
  {
    name: 'CF Rope (13mm dia, 1260°C)',
    sku: 'CFR-13-1260',
    categoryName: 'Ceramic Fiber Textile',
    subCategoryName: 'Ceramic Fiber Rope',
    unit: 'Meter (m)',
    sellingPrice: 95,
    costPrice: 65,
    currentStock: 200,
    minimumStock: 50,
    brand: 'SIMWOOL',
    hsnCode: '70190000',
    taxPercent: 18,
    reinforcementTypes: ['Fiberglass reinforced'],
  },
  {
    name: 'CF Rope (25mm dia, 1260°C)',
    sku: 'CFR-25-1260',
    categoryName: 'Ceramic Fiber Textile',
    subCategoryName: 'Ceramic Fiber Rope',
    unit: 'Meter (m)',
    sellingPrice: 175,
    costPrice: 120,
    currentStock: 150,
    minimumStock: 30,
    brand: 'SIMWOOL',
    hsnCode: '70190000',
    taxPercent: 18,
    reinforcementTypes: ['SS wire reinforced'],
  },
  {
    name: 'CF Cloth (1260°C)',
    sku: 'CFC-1260',
    categoryName: 'Ceramic Fiber Textile',
    subCategoryName: 'Ceramic Fiber Cloth',
    unit: 'Meter (m)',
    sellingPrice: 420,
    costPrice: 290,
    currentStock: 80,
    minimumStock: 20,
    hsnCode: '70190000',
    taxPercent: 18,
  },
  {
    name: 'CF Tape (1260°C, 25mm)',
    sku: 'CFT-25-1260',
    categoryName: 'Ceramic Fiber Textile',
    subCategoryName: 'Ceramic Fiber Tape',
    unit: 'Meter (m)',
    sellingPrice: 85,
    costPrice: 58,
    currentStock: 5,
    minimumStock: 20,
    hsnCode: '70190000',
    taxPercent: 18,
  },
  {
    name: 'HF/CF Insulation Bricks (Hot Face)',
    sku: 'HFCF-HF',
    categoryName: 'Insulation Bricks',
    subCategoryName: 'HF/CF Insulation Bricks',
    unit: 'Piece (pcs)',
    sellingPrice: 65,
    costPrice: 45,
    currentStock: 500,
    minimumStock: 100,
    hsnCode: '69021000',
    taxPercent: 18,
  },
  {
    name: 'HF/CF Insulation Bricks (Cold Face)',
    sku: 'HFCF-CF',
    categoryName: 'Insulation Bricks',
    subCategoryName: 'HF/CF Insulation Bricks',
    unit: 'Piece (pcs)',
    sellingPrice: 55,
    costPrice: 38,
    currentStock: 350,
    minimumStock: 100,
    hsnCode: '69021000',
    taxPercent: 18,
  },
  {
    name: 'HFK Insulation Bricks',
    sku: 'HFK-001',
    categoryName: 'Insulation Bricks',
    subCategoryName: 'HFK Insulation Bricks',
    unit: 'Piece (pcs)',
    sellingPrice: 72,
    costPrice: 50,
    currentStock: 280,
    minimumStock: 50,
    hsnCode: '69021000',
    taxPercent: 18,
  },
  {
    name: 'Porosint Bricks (Grade 23)',
    sku: 'POR-23',
    categoryName: 'Insulation Bricks',
    subCategoryName: 'Porosint Bricks',
    unit: 'Piece (pcs)',
    sellingPrice: 88,
    costPrice: 62,
    currentStock: 0,
    minimumStock: 50,
    hsnCode: '69021000',
    taxPercent: 18,
  },
  {
    name: 'Refractory Mortar (ORTEX)',
    sku: 'RM-ORTEX',
    categoryName: 'Mortars & Castables',
    subCategoryName: 'Refractory Mortar (ORTEX)',
    unit: 'Bag',
    sellingPrice: 950,
    costPrice: 680,
    currentStock: 30,
    minimumStock: 10,
    brand: 'ORTEX',
    hsnCode: '38244000',
    taxPercent: 18,
  },
  {
    name: 'Air Setting Mortar (ORTEX-HT)',
    sku: 'RM-ORTEX-HT',
    categoryName: 'Mortars & Castables',
    subCategoryName: 'Air Setting Mortar (ORTEX-HT)',
    unit: 'Bag',
    sellingPrice: 1200,
    costPrice: 850,
    currentStock: 18,
    minimumStock: 10,
    brand: 'ORTEX',
    hsnCode: '38244000',
    taxPercent: 18,
  },
  {
    name: 'Castable Refractory',
    sku: 'CR-001',
    categoryName: 'Mortars & Castables',
    subCategoryName: 'Castable Refractory',
    unit: 'Bag',
    sellingPrice: 1450,
    costPrice: 980,
    currentStock: 25,
    minimumStock: 8,
    hsnCode: '38244000',
    taxPercent: 18,
  },
  {
    name: 'Fire Blanket (1×1m, 650°C)',
    sku: 'FB-1x1-650',
    categoryName: 'Fire & Welding Protection',
    subCategoryName: 'Fire Blanket',
    unit: 'Piece (pcs)',
    sellingPrice: 1800,
    costPrice: 1200,
    currentStock: 20,
    minimumStock: 5,
    hsnCode: '63049200',
    taxPercent: 18,
  },
  {
    name: 'Fire Blanket (2×2m, 1200°C)',
    sku: 'FB-2x2-1200',
    categoryName: 'Fire & Welding Protection',
    subCategoryName: 'Fire Blanket',
    unit: 'Piece (pcs)',
    sellingPrice: 4500,
    costPrice: 3100,
    currentStock: 8,
    minimumStock: 3,
    hsnCode: '63049200',
    taxPercent: 18,
  },
  {
    name: 'Welding Blanket (2×3m)',
    sku: 'WB-2x3',
    categoryName: 'Fire & Welding Protection',
    subCategoryName: 'Welding Blanket',
    unit: 'Piece (pcs)',
    sellingPrice: 3800,
    costPrice: 2600,
    currentStock: 12,
    minimumStock: 3,
    hsnCode: '63049200',
    taxPercent: 18,
  },
  {
    name: 'Stud & Washer Anchor (SS 304)',
    sku: 'SWA-SS304',
    categoryName: 'Accessories & Services',
    subCategoryName: 'Stud & Washer Anchor',
    unit: 'Piece (pcs)',
    sellingPrice: 45,
    costPrice: 30,
    currentStock: 800,
    minimumStock: 200,
    hsnCode: '73182900',
    taxPercent: 18,
  },
  {
    name: 'Refractory Anchor (SS 310)',
    sku: 'RA-SS310',
    categoryName: 'Accessories & Services',
    subCategoryName: 'Refractory Anchor',
    unit: 'Piece (pcs)',
    sellingPrice: 85,
    costPrice: 58,
    currentStock: 350,
    minimumStock: 100,
    hsnCode: '73182900',
    taxPercent: 18,
  },
];

async function main() {
  const categories = await prisma.category.findMany({ include: { subCategories: true } });
  const catByName = new Map(categories.map((c) => [c.name, c]));

  await prisma.product.deleteMany();

  let created = 0;
  for (const p of products) {
    const cat = catByName.get(p.categoryName);
    if (!cat) {
      console.warn(`Skipping "${p.name}" — category "${p.categoryName}" not found.`);
      continue;
    }
    const sub = cat.subCategories.find((s) => s.name === p.subCategoryName);
    if (!sub) {
      console.warn(`Skipping "${p.name}" — sub-category "${p.subCategoryName}" not found under "${p.categoryName}".`);
      continue;
    }

    await prisma.product.create({
      data: {
        name: p.name,
        sku: p.sku,
        categoryId: cat.id,
        subCategoryId: sub.id,
        unit: p.unit,
        sellingPrice: p.sellingPrice,
        costPrice: p.costPrice,
        currentStock: p.currentStock,
        minimumStock: p.minimumStock,
        brand: p.brand || null,
        hsnCode: p.hsnCode || null,
        description: p.description || null,
        taxPercent: p.taxPercent ?? 18,
        modifiedBy: p.modifiedBy || 'Admin',
        modifiedAt: p.modifiedAt || null,
        densityVariants: p.densityVariants || [],
        boardVariants: p.boardVariants || [],
        thicknessVariants: p.thicknessVariants || [],
        reinforcementTypes: p.reinforcementTypes || [],
      },
    });
    created++;
  }
  console.log(`Seeded ${created} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
