-- AlterTable
ALTER TABLE "clients" ALTER COLUMN "openingBalance" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "creditLimit" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "sellingPrice" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "costPrice" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "taxPercent" SET DATA TYPE DECIMAL(5,2);

-- AlterTable
ALTER TABLE "purchase_items" ALTER COLUMN "qty" SET DATA TYPE DECIMAL(14,3),
ALTER COLUMN "rate" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "purchase_orders" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "freight" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "paidAmount" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "sale_items" ALTER COLUMN "qty" SET DATA TYPE DECIMAL(14,3),
ALTER COLUMN "rate" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "sales_orders" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "paidAmount" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "stock_movements" ALTER COLUMN "qty" SET DATA TYPE DECIMAL(14,3),
ALTER COLUMN "rate" SET DATA TYPE DECIMAL(14,2);

